{
  "hash": "807d8709eea6aecee191745334fda13d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: |\n  Estimating the now and predicting the future: fertility rate estimation and population projection\ndescription: |\n  Use the DHS to estimate fertility levels and project future population levels\nauthor:\n  - name: Rebecca Luttinen\n    affiliation: IPUMS Global Health Data Analyst\n  - name: Elizabeth Heger Boyle\n    affiliation: Professor, Department of Sociology, University of Minnesota\ndate: 05-29-2025\ncategories:\n  - Projections\n  - Population\n  - Fertility\n  - Methodology\n  - R\n  \nfig-width: 10\nfig-height: 8\nbibliography: references.bib\nopen-graph:\n  title: |\n      Estimating the now and predicting the future: fertility rate estimation and population projection\n  description: |\n     Use the DHS to estimate fertility levels and project future population levels\n  #image: images/pathways.png\ntwitter-card:\n  title: |\n     Estimating the now and predicting the future: fertility rate estimation and population projection\n  description: |\n     Use the DHS to estimate fertility levels and project future population levels\n  #image: images/pathways.png\n---\n\n\n\nThe second blog post in our series describes how to use R to estimate fertility rates and to project a population. Understanding the rate of a population process (i.e. fertility) is a key consideration when thinking about the future. A population projection, on the other hand is the result of predicting a future population level. Before we delve into examples of these concepts, let's cover some background information on population data and population-level information.\n\n# **How do we know population-level statistics?**\n\nWith internet access and a smartphone, it is easy to access a statistic about the United States or the world. For example, if you were to use an internet search engine to look up statistics on educational attainment, you may find a [census report from 2022](https://www.census.gov/newsroom/press-releases/2022/educational-attainment.html) that shares that 23.5% of Americans' highest degree was a bachelor's degree in 2022.\n\nJust like any other population-level fact, we are able access counts of people living in a specific place at a given time. The census makes an attempt to count all individuals within most countries every ten years to give us this knowledge. Another way we know this is through **population estimates**, which are generated through applying survey weights to a nationally representative sample of a population.\n\nHow do we estimate future population levels? A systematic approach of predicting future population levels is by creating a population projection. [Our last blog post](https://tech.popdata.org/dhs-research-hub/posts/2025-04-23-forecasting-pt1/) walked users through the proper terminology to use when considering the role of future conditions, introduced this concept and this post will explore it in more detail.\n\n## **Population projections**\n\nA population projection describes the process of using population estimates and other information such as the demographic processes: births, deaths and migration, to generate a future population estimate. There are various statistical methods to project a population, one of which is explored in detail the second workflow of this blog post.\n\n## **Fertility rates**\n\nFertility is a population process that influences future population size. A fertility rate simply summarizes the amount of children per people in a given population. (The most commonly used fertility rates summarize the amount of children per woman.) The fertility rate of a given population is the result of various factors that influence people's fertility-decision-making. The fertility rate of nation can influence the **dependency-ratio,** the ratio of working age adults to children/ retirees, which has implications for a nation's social security system. It is important to note that, fertility is not the only population process that influences population size: migration and mortality do, too.\n\nThis blog post focuses on the prior population process, fertility, and the first workflow demonstrated will walk users through how to use a nationally representative survey to estimate various fertility rates.\n\n# **The importance of the DHS**\n\nOne notable source of data for estimating fertility around the world is the [Demographic and Health Surveys (DHS)](https://www.dhsprogram.com/). The DHS are the principal--and often only--source of vital information on human populations in low- and middle-income countries. Administered from 1984 to 2025, the DHS includes over 400 publicly available cross-sectional household surveys from more than 90 countries.\n\nNationally representative and fielded for countries about every five years, the DHS are lauded for allowing researchers to distinguish between population-level and individual-level factors and for high participation rates, excellent standardized data collection procedures and interviewer training, and the breadth of data collected. [@Corsi2012] The DHS provide population-level statistics on dozens of topics, including:\n\n|                              |                                           |\n|------------------------------|-------------------------------------------|\n| Family structure             | Maternal and newborn care                 |\n| Educational Attainment       | Child health, including vaccinations      |\n| Marriage and sexual activity | Child nutrition                           |\n| Fertility                    | Malaria                                   |\n| Contraception                | HIV knowledge and opinions                |\n| Preferences for family size  | Women's empowerment                       |\n| Infant and child mortality   | Household water and sanitation conditions |\n| Adult mortality              | Wealth and socioeconomic indicators       |\n\nThe most recent DHS also include detailed information on migration, a crucial component of population projections. As of 2025, more than 2000 published [peer-reviewed articles based on DHS data had been reported to ICF](https://www.dhsprogram.com/publications/publication-search.cfm), the organization that administered the program.\n\n[IPUMS DHS](https://www.idhsdata.org/idhs/) is a freely available database that streamlines access and reduces technical barriers to comparative analyses with the DHS. IPUMS DHS harmonizes DHS variables across surveys and makes crucial documentation easily accessible, greatly reducing researchers' data-management tasks. Researchers constructing population projections across multiple countries may want to consider accessing DHS through IPUMS.\n\n# **How to generate fertility estimates**\n\nThis blog post walks users through how to use DHS data to generate various forms of fertility rates. This example will use the most recent women’s file in Kenya, which is from the year 2022. This year is not uploaded to IPUMS DHS at this time, so this portion of the analysis uses the raw DHS women’s individual recode (IR) file. \n\nWe use the [DHS.rates()](https://www.rdocumentation.org/packages/DHS.rates/versions/0.9.2) package to calculate the **general fertility rate (GFR)**, the **age-specific fertility rates (ASFR)** for five-year age groups and a **total fertility rate (TFR)**. This package was developed to allow users to calculate key indicators of DHS data at the national or at various domain levels (such as urban vs. rural, educational attainment, or region).\n\n::: column-margin\nThe DHS.rates() package was designed for standard DHS file types, however as long as the data extract includes the necessary information to calculate a fertility rate (i.e. birth history data) it will work. This package can also be used with surveys other than the DHS, as long as they include the necessary information.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load libraries\nlibrary(haven)\nlibrary(dplyr)\nlibrary(DHS.rates)\n#> Warning: package 'DHS.rates' was built under R version 4.4.3\n```\n:::\n\n\n\nFirst, we read in our data.\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#read in data\nkenya22<-read_dta(\"data/Kenya2022/KEIR8BDT/KEIR8BFL.DTA\")\n\nkenya22<-zap_labels(kenya22)\n```\n:::\n\n\n\nAn important consideration in estimating a fertility rate is whether you are interested in a period or cohort rate. A period rate considers the rate for fertility over a specific interval of time. A cohort rate can either be calculated by 1) following a group of women throughout their lifespan and counting their births; or 2) it can be calculated by creating synthetic cohorts and considering parity at the time of survey their number of children at a given time.\n\nWe calculate two period rates: the general fertility rate and age-specific. Then we calculate a synthetic cohort rate, the total fertility rate. The GFR is calculated using the following equation:\n\n *GFR=(Number of live births in a year / Number of women aged 15-44 in the same year)*\n\nThe GFR is calculated as the total number of births during an interval of time (the reference period) divided by the total number of women-years of exposure, based on all women in their reproductive years, aged 15–44 during the same interval of time. [@Elkasabi2019] You can tell the fert() function to calculate this by including 'Indicator=\"gfr\" in your code. This function will calculate the reference period. It will also print out the standard error (SE), the number of observations (N), the weighted number of observations (WN), the standard error design effect (DEFT), the relative standard error (RSE), and the confidence interval (lower confidence interval=LCI & upper confidence interval= UCI).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#use the fert function to calculate various fertilty rates\n\n#General Fertiltiy Rate\n\nGeneral_Fertility_Rate <- fert(\n kenya22,\n Indicator = \"gfr\"\n)\n#> \n#>  The current function calculated GFR based on a reference period of 36 months \n#>  The reference period ended at the time of the interview, in 2022.33 OR Feb - Jul 2022 \n#>  The average reference period is 2020.83\n\nGeneral_Fertility_Rate\n#>          GFR    SE     N    WN  DEFT   RSE     LCI     UCI\n#> [1,] 121.266 1.634 85634 86313 1.496 0.013 118.062 124.469\n```\n:::\n\n\n\n::: column-margin\nThe default reference period in the fert() function is 36 months. It can be adjusted if you specify it in your code ('Period=' and 'PeriodEnd='). See this [report](https://cran.rstudio.com/web/packages/DHS.rates/DHS.rates.pdf) for more information.\n:::\n\nThe ASFR, similar to the GFR, summarizes the amount of children being born during a time interval per the amount of women years of exposure, but it does so by specific age group. The typical grouping strategy for this is to break up age into five year categories (15-19, 20-24, 25-29, 30-34, 35-39, 40-44, and 45-49). [@Elkasabi2019]\n\nThe ASFR uses the following equation:\n\n*ASFR= (Number of live births to women age a-age a+4/ women-years during the reference period) \\* 1,000*\n\n::: callout-note\nThe ASFR is multiplied by 1,000 because it is interpreted as per 1,000 women.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Age Specific Fertility Rate\n\nAge_Specific_Fertility_Rate <- fert(\n kenya22,\n Indicator = \"asfr\"\n)\n#> \n#>  The current function calculated ASFR based on a reference period of 36 months \n#>  The reference period ended at the time of the interview, in 2022.33 OR Feb - Jul 2022 \n#>  The average reference period is 2020.83\n\nAge_Specific_Fertility_Rate\n#>     AGE    ASFR    SE     N    WN  DEFT   RSE     LCI     UCI\n#> 0 15-19  73.169 2.573 18693 18333 1.356 0.035  68.127  78.211\n#> 1 20-24 178.609 4.220 16996 17654 1.523 0.024 170.338 186.879\n#> 2 25-29 172.145 4.384 15357 15695 1.529 0.025 163.553 180.737\n#> 3 30-34 137.389 4.212 14167 14146 1.538 0.031 129.133 145.646\n#> 4 35-39  86.690 3.623 11282 11325 1.369 0.042  79.589  93.792\n#> 5 40-44  34.877 2.764  9139  9158 1.401 0.079  29.459  40.294\n#> 6 45-49   5.314 1.056  4850  4806 1.008 0.199   3.244   7.385\n```\n:::\n\n\n\nThe TFR is a synthetic measure that summarizes the ASFRs into one age-standardized rate. A TFR can be interpreted as the number of children who would be born per woman if she were to have children according to each age-specific rate throughout her reproductive years. This is summarized in the following equation:\n\n*TFR= 5\\* (sum of each ASFR)/1,000*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Fertility Rate\n\nTotal_Fertility_Rate <- fert(\n kenya22,\n Indicator = \"tfr\",\n)\n#> \n#>  The current function calculated TFR based on a reference period of 36 months \n#>  The reference period ended at the time of the interview, in 2022.33 OR Feb - Jul 2022 \n#>  The average reference period is 2020.83\n\nTotal_Fertility_Rate\n#>        TFR     N    WN\n#> [1,] 3.441 90484 91119\n```\n:::\n\n\n\nThe 'class=' option in the fert() function allows you to calculate rates based on certain characteristics. Below we've calculated the TFR based on urban vs. rural status. The DHS codebook tells us that 1=urban and 2= rural. The between fertility rates between urban and rural areas of almost one child is in line with literature on fertility in sub-Saharan Africa. [@Lerch2019; @Shapiro2017]\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Let's compare the urban and rural total fertilty rate\n\nTotal_Fertility_Rate_urban_vs_rural <- fert(\n kenya22,\n Indicator = \"tfr\",\n Class= \"v025\"\n)\n#> \n#>  The current function calculated TFR based on a reference period of 36 months \n#>  The reference period ended at the time of the interview, in 2022.33 OR Feb - Jul 2022 \n#>  The average reference period is 2020.83\n\nTotal_Fertility_Rate_urban_vs_rural\n#>   Class   TFR     N    WN\n#> 1     1 2.842 35442 38137\n#> 2     2 3.941 55042 52982\n```\n:::\n\n\n\n::: callout-note\nThe TFR is multiplied by 5 because the ASFRs are in five-year intervals.\n:::\n\nThe DHS is not only useful in calculating current and historical rates, it can also be used to project a future population.\n\n# **Population Projections: An Introduction**\n\nThe second workflow in this blog post walks users through how to project a population of women in their reproductive years (aged 15-49) using the Hamilton-Perry method. This method is useful if you don't have information on all population processes because it assumes fertility, migration, and mortality are constant. In reality, these processes are ever-evolving and changing, so the Hamilton-Perry method will be less reliable than projection methods that take changing trends into account.\n\nThis method requires at least two population estimates from different time points. In this method, a demographer would calculate the **cohort-change ratio (CCR)** using the population levels at each point. This can be achieved by dividing one of the population counts at the most recent time by the population at the earlier time period. The resulting value is the CCR. The demographer can then multiply the CCR by their base population count, to generate the forecast of a given year. [@Swanson2017]\n\n# **How to project a population using the Hamilton-Perry method**\n\nFor our second workflow we use the 2001, 2006, and 2011 women's files in Uganda to project the total population in 2016. We then compare our population projection to the DHS estimate from the 2016 survey.\n\nWe source this data from IPUMS DHS.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load libraries\n\nlibrary(ipumsr)\nlibrary(stats)\nlibrary(dplyr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#read in data extract from IPUMS DHS\n\nuganda_dhs <- read_ipums_micro(\"data/idhs_00004.xml\")\n#> Use of data from IPUMS DHS is subject to conditions including that users should cite the data appropriately. Use command `ipums_conditions()` for more details.\n```\n:::\n\n\n\nWe will use the aggregate() function from the dplyr package to sum the POPWT to estimate the total population of women in their reproductive years (aged 15-49).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n\nuganda_pop<-aggregate(uganda_dhs$POPWT, by= list(uganda_dhs$YEAR), FUN = \"sum\")\n\nuganda_pop\n#>   Group.1       x\n#> 1    1988 3610171\n#> 2    1995 4478497\n#> 3    2001 5309989\n#> 4    2006 6428314\n#> 5    2011 7763897\n#> 6    2016 9407944\n```\n:::\n\n\n\nIn the Hamilton-Perry method of population projection you need at least two different observations of a population estimate. When working with more than two observations of population estimates, It is important to keep the interval between years the same. We will use 2001, 2006 and 2011 to project 2016's population. We will then compare our projeciton to the DHS estimation for 2016 and other published estimates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the cohort-change ratio\n\n#from 2001-2006\n6428314/5309989\n#> [1] 1.210608\n\n#from 2006-2011\n7763897/6428314\n#> [1] 1.207766\n\n#Take the average of the two\n\nmean(1.210608, 1.207766)\n#> [1] 1.210608\n\n#Multiply the average by the population in 2011\n\n1.210608*7763897\n#> [1] 9399036\n```\n:::\n\n\n\nOur projection yields that 9,399,036 women in their reproductive years were living in Uganda in 2016. The DHS estimation for this population in 2016 is slightly higher at 9,407,944.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#get the difference between our population projection and the DHS 2016 estimate\n 9407944-9399036 \n#> [1] 8908\n \n #Calculate the percent difference between them\n \n((9399036-9407944)/ 9407944)*100\n#> [1] -0.09468594\n```\n:::\n\n\n\nOur estimate was off by just under 9,000 women. While this number may seem relatively large, the percent difference shows us that is less than a 10% difference. The first part of this blog post shows us how to generate various fertility rates. If we had access to data on the other population processes, such as the rate of mortality and migration, we would be able to use the cohort-component method.\n\n::: column-margin\nAnother source of population estimates for middle- and low-income countries is the [United Nations Population Division.](https://population.un.org/dataportal/home?df=98d323f2-2989-48e5-86b5-6f3054bb581d)\n:::\n\n# **Other methods**\n\n## **Cohort-component method**\n\nOne example of projecting a population is called the cohort component method. The cohort component method utilizes two important demographic concepts: the life table and the demographic equation of population change. This **cohort component method** is considered as the most comprehensive method of population projection, as it essentially maps out the *basic demographic equation of population change: (population at time t+1= population at time t + births at t – D deaths at time t + in-migration at time t – outmigration at time t).* [@Carmichael2016]\n\n## **Mathematical model approaches**\n\nAnother method of population projection involves fitting a mathematical model to population data. This approach does not disaggregate data by age and sex, but rather considers the total population. [@Yusuf2014]  \n\nSome examples of the types of models used in this approach are linear, logistic, and exponential. In a linear approach, signified by this equation: *Y=a+b\\*X*, b would be an indicator of population growth. [@Yusuf2014] In this equation y= the population, x= time (usually in years), and a= the intercept. Both a linear approach and the cohort-change ratio assume that the rate of change within a population is constant. In real life, however, these rates are not constant, as there are **period effects**, which are caused by events that influence people at a certain point in time.\n\nA mathematical approach that does not assume a constant rate over time is called the **Gompertz model.** This model uses an **asymptote** to indicate an upper limit for population size. The Gompertz model uses the following equation to project a population: *log(Y)=log(k) +log(a)\\*bx.* In this equation Y=population, X is a measure of time, k is an asymptote setting a limit for the population, and a and b are parameters of the population. [@Yusuf2014]\n\n# Conclusion\n\nThis is the second post in a four-part series on methods of future estimation and how they can be applied to child health and climate research. We first highlighted the DHS as a critically important data source for population-level knowledge particularly focused on child and women's health in many low- and middle-income countries. Then we demonstrated how to use the DHS.rates() package to calculate various fertility rates. Lastly, we demonstrated how to use DHS data sourced from IPUMS to project a future population estimate. Stay tuned for the next post in this series, which will be focused on how to use methods of future estimation in climate research.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}