<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Finn Roberts">
<meta name="author" content="Matt Gunther">
<meta name="dcterms.date" content="2024-02-04">
<meta name="description" content="Remotely sensed precipitation data can provide important context for understanding the health outcomes reported in the DHS">

<title>Attaching CHIRPS Precipitation Data to DHS Surveys – IPUMS DHS Spatial Analysis and Health Research Hub</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon/favicon-32x32.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0WLH5S9VD5"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-0WLH5S9VD5', { 'anonymize_ip': true});
</script>


<meta property="og:title" content="Attaching CHIRPS Precipitation Data to DHS Surveys">
<meta property="og:description" content="Remotely sensed precipitation data can provide important context for understanding the health outcomes reported in the DHS">
<meta property="og:image" content="https://ipums.github.io/dhs-research-hub/posts/2024-02-04-dhs-chirps/index_files/figure-html/listing-img-1.png">
<meta property="og:site_name" content="IPUMS DHS Spatial Analysis and Health Research Hub">
<meta property="og:image:height" content="1536">
<meta property="og:image:width" content="1920">
<meta name="twitter:title" content="Attaching CHIRPS Precipitation Data to DHS Surveys">
<meta name="twitter:description" content="Remotely sensed precipitation data can provide important context for understanding the health outcomes reported in the DHS">
<meta name="twitter:image" content="https://ipums.github.io/dhs-research-hub/posts/2024-02-04-dhs-chirps/index_files/figure-html/listing-img-1.png">
<meta name="twitter:image-height" content="1536">
<meta name="twitter:image-width" content="1920">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="https://www.idhsdata.org/idhs/" class="navbar-brand navbar-brand-logo">
    <img src="../../images/dhs_logo_white.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Spatial Analysis and Health Research Hub</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-getting-started" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Getting Started</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-getting-started">    
        <li>
    <a class="dropdown-item" href="../../posts/2024-02-01-getting-started-with-r/index.html">
 <span class="dropdown-text">An Introduction to R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../posts/2024-02-02-download-dhs-data/index.html">
 <span class="dropdown-text">Obtaining IPUMS DHS Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-community" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Community</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-community">    
        <li>
    <a class="dropdown-item" href="https://forum.ipums.org">
 <span class="dropdown-text">IPUMS Forum</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../CODE_OF_CONDUCT.html">
 <span class="dropdown-text">Code of Conduct</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../LICENSE.html">
 <span class="dropdown-text">License</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/ipums/dhs-research-hub"> 
<span class="menu-text"><i class="fa-brands fa-github" aria-label="github"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.xml"> 
<span class="menu-text"><i class="fa-solid fa-rss" aria-label="rss"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://twitter.com/ipumsGH"> 
<span class="menu-text"><i class="fa-brands fa-x-twitter" aria-label="x-twitter"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://forum.ipums.org"> 
<span class="menu-text"><i class="fa-solid fa-users" aria-label="users"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.ipums.org/"> 
<span class="menu-text"><i class="fa-solid fa-globe" aria-label="globe"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Attaching CHIRPS Precipitation Data to DHS Surveys</h1>
                  <div>
        <div class="description">
          <p>Remotely sensed precipitation data can provide important context for understanding the health outcomes reported in the DHS</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">CHIRPS</div>
                <div class="quarto-category">Precipitation</div>
                <div class="quarto-category">Extreme weather</div>
                <div class="quarto-category">Agriculture</div>
                <div class="quarto-category">terra</div>
                <div class="quarto-category">sf</div>
                <div class="quarto-category">ggspatial</div>
                <div class="quarto-category">R</div>
              </div>
                  </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-heading">Affiliations</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">Finn Roberts </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Senior Data Analyst, IPUMS
            </p>
        </div>
      <div class="quarto-title-meta-contents">
      <p class="author">Matt Gunther </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Research Methodologist, NORC
            </p>
        </div>
    </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 4, 2024</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">April 15, 2024</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#outline" id="toc-outline" class="nav-link active" data-scroll-target="#outline">Outline</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data sources</a>
  <ul class="collapse">
  <li><a href="#ipums-dhs-survey-data" id="toc-ipums-dhs-survey-data" class="nav-link" data-scroll-target="#ipums-dhs-survey-data">IPUMS DHS survey data</a></li>
  <li><a href="#dhs-cluster-coordinates" id="toc-dhs-cluster-coordinates" class="nav-link" data-scroll-target="#dhs-cluster-coordinates">DHS cluster coordinates</a>
  <ul class="collapse">
  <li><a href="#vector-data" id="toc-vector-data" class="nav-link" data-scroll-target="#vector-data">Vector data</a></li>
  <li><a href="#loading-cluster-coordinates" id="toc-loading-cluster-coordinates" class="nav-link" data-scroll-target="#loading-cluster-coordinates">Loading cluster coordinates</a></li>
  <li><a href="#visualizing" id="toc-visualizing" class="nav-link" data-scroll-target="#visualizing">Visualizing spatial data</a></li>
  </ul></li>
  <li><a href="#chirps-precipitation-data" id="toc-chirps-precipitation-data" class="nav-link" data-scroll-target="#chirps-precipitation-data">CHIRPS precipitation data</a>
  <ul class="collapse">
  <li><a href="#raster-data" id="toc-raster-data" class="nav-link" data-scroll-target="#raster-data">Raster data</a></li>
  <li><a href="#loading-chirps-data" id="toc-loading-chirps-data" class="nav-link" data-scroll-target="#loading-chirps-data">Loading CHIRPS data</a></li>
  <li><a href="#spatraster-objects" id="toc-spatraster-objects" class="nav-link" data-scroll-target="#spatraster-objects"><code>SpatRaster</code> objects</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summarize-precipitation-values" id="toc-summarize-precipitation-values" class="nav-link" data-scroll-target="#summarize-precipitation-values">Summarize precipitation values</a>
  <ul class="collapse">
  <li><a href="#cluster-buffers" id="toc-cluster-buffers" class="nav-link" data-scroll-target="#cluster-buffers">Cluster buffers</a></li>
  <li><a href="#aggregating-rainfall-within-cluster-regions" id="toc-aggregating-rainfall-within-cluster-regions" class="nav-link" data-scroll-target="#aggregating-rainfall-within-cluster-regions">Aggregating rainfall within cluster regions</a>
  <ul class="collapse">
  <li><a href="#scaling-up-for-all-clusters" id="toc-scaling-up-for-all-clusters" class="nav-link" data-scroll-target="#scaling-up-for-all-clusters">Scaling up for all clusters</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#join-data-sources" id="toc-join-data-sources" class="nav-link" data-scroll-target="#join-data-sources">Join data sources</a></li>
  <li><a href="#final-thoughts" id="toc-final-thoughts" class="nav-link" data-scroll-target="#final-thoughts">Final thoughts</a>
  <ul class="collapse">
  
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<p>We know that health outcomes are significantly impacted by individuals’ environmental context: excessive rainfall can flood local infrastructure<span class="citation" data-cites="Mirza2011"><sup><a href="#ref-Mirza2011" role="doc-biblioref">1</a></sup></span>; warmer temperatures can expand the range of common disease vectors<span class="citation" data-cites="Martens1997"><sup><a href="#ref-Martens1997" role="doc-biblioref">2</a></sup></span>; and drought can decimate crop-growing regions.<span class="citation" data-cites="Lesk2016"><sup><a href="#ref-Lesk2016" role="doc-biblioref">3</a></sup></span> However, survey data like those from <a href="https://www.dhsprogram.com/">The DHS Program</a> often provide only a limited view of the environmental trends in which individuals are embedded.</p>
<p>Developing a more holistic understanding of the role of environmental conditions in health outcomes therefore requires integrating external data sources with the survey data from DHS.</p>
<p>In this post we’ll demonstrate how to obtain raw precipitation data from the <a href="https://www.chc.ucsb.edu/data/chirps">Climate Hazards Center InfraRed Precipitation with Station dataset</a> (CHIRPS) and attach that data to survey responses from <a href="https://www.idhsdata.org/idhs/">IPUMS DHS</a>.</p>
<section id="outline" class="level1 page-columns page-full">
<h1>Outline</h1>
<p>As a motivating example, we’ll consider whether historical precipitation rates have an effect on child stunting in Burkina Faso, measured with height-for-age Z-scores. Precipitation patterns in an area likely influence crop yields for local farms. Thus, by impairing food production, periods of low precipitation may also be related to child stunting.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The height-for-age Z-score represents the difference between the child’s height and the median height of a reference population of the same age and sex, expressed in standard deviation units.</p>
</div></div><p>To address this question, we will first need to gather data from several sources. In the <a href="#data-sources">Data sources</a> section, we demonstrate how to obtain</p>
<ul>
<li>DHS survey data from IPUMS DHS.</li>
<li>GPS coordinate data for DHS survey areas from The DHS Program.</li>
<li>daily precipitation data for 2001-2010 from CHIRPS.</li>
</ul>
<p>Next, in the <a href="#summarize-precipitation-values">Summarize precipitation values</a> section, we’ll summarize the daily precipitation data in the area around each DHS survey location. To do this, we’ll</p>
<ul>
<li>average the daily precipitation values across the 10-year time period to produce an estimate of the average millimeters of rainfall per day.</li>
<li>define a buffer region around each DHS survey location, allowing us to capture the trends in precipitation in the general vicinity of each survey location.</li>
<li>aggregate the precipitation data spatially to produce a single estimate of the average daily precipitation for each DHS survey area.</li>
</ul>
<p>Finally, in the <a href="#join-data-sources">Join data sources</a> section, we’ll attach the aggregated precipitation values for each survey area to the DHS survey responses from that area.</p>
</section>
<section id="data-sources" class="level1 page-columns page-full">
<h1>Data sources</h1>
<section id="ipums-dhs-survey-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="ipums-dhs-survey-data">IPUMS DHS survey data</h2>
<p>To get started, we’ll download a data file (or <em>extract</em>, in IPUMS terms) from IPUMS DHS and load it into R. The extract in this post contains the <code>HWHAZWHO</code> variable (which contains the height-for-age Z-score) along with several pre-selected variables for the <strong>2010 Burkina Faso</strong> sample. If you need a refresher on how to download IPUMS DHS data, see the <a href="../2024-02-02-download-dhs-data/index.html">Downloading IPUMS DHS Data</a> post.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p></p><div class="hex"> <a href="https://tech.popdata.org/ipumsr/" class="hex"> <img src="../../images/hex/ipumsr.png" class="hex-img"> </a> <p class="hex-cap">© IPUMS (MPL-2.0)</p> </div><p></p>
</div></div><p>We’ve downloaded and stored our XML codebook and compressed data file in the <code>data/dhs</code> directory. Be sure to update this path based on your local file setup, so you can follow along.</p>
<p>To simplify our output, we’ll select only a subset of the variables included in the extract:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ipumsr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load IPUMS DHS extract</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>dhs <span class="ot">&lt;-</span> <span class="fu">read_ipums_micro</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ddi =</span> <span class="st">"data/dhs/idhs_00018.xml"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data_file =</span> <span class="st">"data/dhs/idhs_00018.dat.gz"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="cn">FALSE</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Select a subset of variables</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>dhs <span class="ot">&lt;-</span> dhs <span class="sc">|&gt;</span> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SAMPLE, YEAR, IDHSPID, IDHSHID, DHSID, URBAN, HWHAZWHO)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>dhs</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 15,044 × 7</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    SAMPLE                     YEAR IDHSPID      IDHSHID DHSID URBAN   HWHAZWHO  </span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;int+lbl&gt;                 &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt; &lt;int+l&gt; &lt;int+lbl&gt; </span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… -264      </span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… -113      </span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur…  -13      </span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… -291      </span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… -211      </span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… 9999 [NIU…</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… 9999 [NIU…</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… -185      </span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur… 9999 [NIU…</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 85404 [Burkina Faso 2010]  2010 85404      … 85404 … BF20… 2 [Rur…  -88      </span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # ℹ 15,034 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This gives us a tabular data source containing 15,044 individual DHS survey responses for 7 variables. Of particular note is the <code>DHSID</code> variable (which stores the identifier for the location of the survey response).</p>
</section>
<section id="dhs-cluster-coordinates" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="dhs-cluster-coordinates">DHS cluster coordinates</h2>
<p>To meaningfully attach environmental data to our DHS survey responses, we’ll need to know the location where each survey response was collected. Fortunately, the DHS Program provides GPS coordinates for each surveyed household grouping, or <em>cluster</em>.</p>
<div id="displacement-rules" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
DHS Cluster Displacement
</div>
</div>
<div class="callout-body-container callout-body">
<p>It’s important to note that the GPS coordinates provided by The DHS Program do not actually reflect the exact location of the clusters. In fact, the coordinates provided are <strong>randomly displaced</strong> from their true locations, such that:</p>
<ul>
<li>urban clusters are displaced up to 2 kilometers in any direction.</li>
<li>99% of rural clusters are displaced up to 5 kilometers in any direction.</li>
<li>1% of rural clusters are displaced up to 10 kilometers in any direction.</li>
<li>displaced coordinates do not cross the country boundary and stay within the DHS survey region.</li>
</ul>
<p>The current demonstration doesn’t require a precise location of each cluster, so we will ignore this detail. However, for more fine-grained analyses (e.g.&nbsp;road network analyses), you may need to take displacement into account.</p>
<p>See the DHS <a href="https://www.dhsprogram.com/Methodology/GPS-Data.cfm">GPS data collection</a> documentation for more details about the DHS cluster point displacement methodology.</p>
</div>
</div>
<p>IPUMS DHS does not yet disseminate DHS cluster coordinates directly. For now, to obtain the GPS coordinates for a specific sample, you’ll have to <a href="https://dhsprogram.com/data/dataset_admin/login_main.cfm?CFID=213299554&amp;CFTOKEN=6d266879cd82102d-25F5B67E-C2E2-57E8-ECA142BF3516BEDD">log into</a> your account from The DHS Program. Specify your country of interest, and, on the line for the appropriate sample year, click the link to download the GPS coordinate data under the heading <strong>GPS Datasets</strong>. (Again, for this example, we’re using Burkina Faso’s 2010 sample.)</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>IPUMS DHS has recently received permission and funding to distribute DHS GPS data. Stay tuned, as these data will soon be available via IPUMS!</p>
</div></div><p>You’ll be presented with a new page containing a list of download links. Scroll down to the <strong>Geographic Datasets</strong> section. You have the option of downloading the file as either a shapefile (.shp) or a comma delimited file (.csv). For our purposes, we will download the <strong>shapefile</strong>, which contains spatial information in a format that can be easily interpreted by R (as well as by external GIS software).</p>
<p>For the Burkina Faso 2010 sample, the file should be named <code>BFGE61FL</code>. If you see a different file name, make sure you’re working with the correct survey year.</p>
<section id="vector-data" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="vector-data">Vector data</h3>
<p>Our DHS cluster coordinates are what’s known as <strong>vector data</strong>. Vector data refer to spatial data that represent geographic features using geometric shapes like points, lines, and polygons.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/plp1.png" class="img-fluid figure-img"></p>
<figcaption>Basic features of the vector data model<span class="citation" data-cites="Minn"><sup><a href="#ref-Minn" role="doc-biblioref">4</a></sup></span></figcaption>
</figure>
</div>
<p>In R, the <code>{sf}</code> package provides an intuitive tabular framework for working with vector data. sf objects look much like a familiar <code>{tibble}</code> or <code>data.frame</code>, but also include an additional <code>geometry</code> column, which stores the spatial features that correspond to each set of observations.</p>

<!-- ::: column-margin -->
<!-- sf stands for "[simple -->
<!-- features](https://en.wikipedia.org/wiki/Simple_Features)", a concept -->
<!-- used commonly in geographic information systems (GIS). -->
<!-- ::: -->
<div class="no-row-height column-margin column-container"><div class="">
<p></p><div class="hex"> <a href="https://r-spatial.github.io/sf/index.html" class="hex"> <img src="../../images/hex/sf.png" class="hex-img"> </a> <p class="hex-cap">© Edzer Pebesma (GPL-2 | MIT)</p> </div><p></p>
</div></div><section id="installing-sf" class="level4">
<h4 class="anchored" data-anchor-id="installing-sf">Installing sf</h4>
<p>sf requires three <strong>operating system dependencies</strong>:</p>
<ul>
<li><a href="https://trac.osgeo.org/geos">GEOS</a> for geometrical operations on projected coordinates</li>
<li><a href="http://proj.org/">PRØJ</a> for coordinate reference system conversion and transformation</li>
<li><a href="http://www.gdal.org/">GDAL</a> for driver options</li>
</ul>
<p>Make sure to follow <a href="https://r-spatial.github.io/sf/index.html#installing">these instructions</a> to ensure that you set up <code>GEOS</code>, <code>PRØJ</code>, and <code>GDAL</code> when installing sf. The installation instructions may vary slightly, depending on your operating system. You may also need to update R, and then run <code>install.packages("sf")</code>.</p>
</section>
</section>
<section id="loading-cluster-coordinates" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="loading-cluster-coordinates">Loading cluster coordinates</h3>
<p>Once sf is installed, we can use <code>st_read()</code> to load the file of GPS coordinate data we downloaded above. We’ve stored our shapefile in the <code>data/gps</code> directory. Again, make sure to adjust this path based on the location where you saved the file on your own system.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>A shapefile is actually a <em>collection</em> of several files; the primary file will have the .shp extension. Other files contain relevant metadata about the geometries contained in the .shp file (for instance, projection or index information).</p>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the 2010 BF cluster coordinate shapefile</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>bf_gps <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/gps/BFGE61FL/BFGE61FL.shp"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Reading layer `BFGE61FL' from data source </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   `/Users/robe2037/Documents/projects/dhs-research-hub/posts/2024-02-04-dhs-chirps/data/gps/BFGE61FL/BFGE61FL.shp' </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   using driver `ESRI Shapefile'</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Simple feature collection with 573 features and 20 fields</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geometry type: POINT</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dimension:     XY</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Bounding box:  xmin: -5.426079 ymin: 5.684342e-14 xmax: 1.957316 ymax: 14.86258</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geodetic CRS:  WGS 84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our resulting dataset looks something like a <code>tibble</code>, except that it contains a header describing a <strong>simple feature collection</strong> with 573 <em>features</em> and 20 <em>fields</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>bf_gps</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Simple feature collection with 573 features and 20 fields</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geometry type: POINT</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dimension:     XY</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Bounding box:  xmin: -5.426079 ymin: 5.684342e-14 xmax: 1.957316 ymax: 14.86258</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geodetic CRS:  WGS 84</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; First 10 features:</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             DHSID DHSCC DHSYEAR DHSCLUST CCFIPS ADM1FIPS ADM1FIPSNA ADM1SALBNA</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1  BF201000000001    BF    2010        1     UV     NULL       NULL       NULL</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2  BF201000000002    BF    2010        2     UV     NULL       NULL       NULL</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3  BF201000000003    BF    2010        3     UV     NULL       NULL       NULL</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4  BF201000000004    BF    2010        4     UV     NULL       NULL       NULL</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5  BF201000000005    BF    2010        5     UV     NULL       NULL       NULL</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6  BF201000000006    BF    2010        6     UV     NULL       NULL       NULL</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7  BF201000000007    BF    2010        7     UV     NULL       NULL       NULL</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8  BF201000000008    BF    2010        8     UV     NULL       NULL       NULL</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9  BF201000000009    BF    2010        9     UV     NULL       NULL       NULL</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 BF201000000010    BF    2010       10     UV     NULL       NULL       NULL</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ADM1SALBCO ADM1DHS ADM1NAME DHSREGCO          DHSREGNA SOURCE URBAN_RURA</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1        NULL    9999     NULL       13         Sud-Ouest    GPS          R</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2        NULL    9999     NULL        2          Cascades    GPS          R</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3        NULL    9999     NULL       13         Sud-Ouest    GAZ          U</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4        NULL    9999     NULL       10              Nord    GPS          R</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5        NULL    9999     NULL        1 Boucle de Mouhoun    GPS          R</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6        NULL    9999     NULL        6      Centre-Ouest    GPS          R</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7        NULL    9999     NULL       12             Sahel    GPS          R</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8        NULL    9999     NULL        3            Centre    GPS          U</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9        NULL    9999     NULL        4        Centre-Est    GPS          U</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10       NULL    9999     NULL        5       Centre-Nord    GAZ          R</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       LATNUM   LONGNUM ALT_GPS ALT_DEM DATUM                   geometry</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1  10.109415 -2.807555     269     269 WGS84 POINT (-2.807555 10.10942)</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2  10.388513 -3.907798     367     362 WGS84 POINT (-3.907798 10.38851)</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3   9.882864 -2.925703    9999     308 WGS84 POINT (-2.925703 9.882864)</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4  13.573418 -2.163120     323     323 WGS84  POINT (-2.16312 13.57342)</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5  12.453299 -3.461899     301     298 WGS84  POINT (-3.461899 12.4533)</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6  12.045308 -2.083828     338     325 WGS84 POINT (-2.083828 12.04531)</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7  14.354198 -0.672096     328     328 WGS84  POINT (-0.672096 14.3542)</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8  12.311034 -1.562071     322     324 WGS84 POINT (-1.562071 12.31103)</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9  11.780763 -0.363904     317     304 WGS84 POINT (-0.363904 11.78076)</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 13.225114 -1.337994    9999     343 WGS84 POINT (-1.337994 13.22511)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Each feature corresponds to one cluster location for which we have GPS coordinates, and each field represents a variable measured for each cluster. At the end of the output, you’ll also notice the aforementioned <code>geometry</code> column that contains the latitude and longitude for each displaced cluster location.</p>
<p>Some clusters contain unverified coordinates and have been assigned a location of (0, 0). Since we have no way of linking these clusters to environmental data, we will remove them for this analysis using dplyr’s <code>filter()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove empty geographies</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>bf_gps <span class="ot">&lt;-</span> bf_gps <span class="sc">|&gt;</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LATNUM <span class="sc">!=</span> <span class="dv">0</span>, LONGNUM <span class="sc">!=</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualizing" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="visualizing">Visualizing spatial data</h3>
<p>It’s always worth double-checking that spatial data are being processed as expected, and this is often most easily done visually. We’ll use the <code>{ggspatial}</code> package to visualize our spatial data. This package is a convenient extension of the popular <code>{ggplot2}</code> package.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p></p><div class="hex"> <a href="https://ggplot2.tidyverse.org/index.html" class="hex"> <img src="../../images/hex/ggplot2.png" class="hex-img"> </a> <p class="hex-cap">© RStudio, Inc. (MIT)</p> </div><p></p>
</div></div><p>As with ggplot2, ggspatial allows us to think of our plot in layers. The primary difference is that ggspatial’s <code>layer_spatial()</code> automatically maps the plot’s x and y dimensions to the geographic coordinates in the data.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
ggplot2 and Themes
</div>
</div>
<div class="callout-body-container callout-body">
<p>This post isn’t intended to be an introduction to ggplot2, so don’t worry if some of the plot code is unfamiliar to you—you should still be able to follow along with the other content in the post.</p>
<p>Also, we’ve modified some of the default theme elements for use in our plots throughout this post. We won’t cover all the details here, but note that your plots will likely look a bit different if you’re following along. For more about themes, see the associated <a href="https://ggplot2.tidyverse.org/reference/theme.html">documentation</a>.</p>
</div>
</div>
<p>To add some context to our map, we’ll load a shapefile containing the Burkina Faso administrative borders. We’ll use the integrated geographies provided by IPUMS, which can be downloaded by clicking the <strong>shapefile</strong> link under the <strong>Burkina Faso</strong> section of <a href="https://www.idhsdata.org/idhs/gis.shtml">this table</a>. We’ve placed this shapefile alongside our DHS coordinate data in our <code>data/gps</code> directory, and can load it with <code>st_read()</code>, as we did before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load administrative boundary shapefile</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>bf_borders <span class="ot">&lt;-</span> <span class="fu">st_read</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/gps/geo_bf2003_2010/geo_bf2003_2010.shp"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">quiet =</span> <span class="cn">TRUE</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can plot the cluster locations (stored in <code>bf_gps</code>) along with the Burkina Faso administrative boundaries (stored in <code>bf_borders</code>):</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggspatial)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create map with cluster locations and BF boundaries </span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_borders, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_gps, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Approximate DHS Cluster Locations"</span>, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Burkina Faso: 2010"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: DHS Program"</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_scale</span>(</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">style =</span> <span class="st">"ticks"</span>, <span class="at">location =</span> <span class="st">"br"</span>), </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_col =</span> <span class="st">"#999999"</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">line_col =</span> <span class="st">"#999999"</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>So far, everything seems to be working as expected—all the cluster points fall within the national borders, and there are noticeably more points in known urban areas, like the capital region of Ouagadougou. We should be safe to continue and load our precipitation data.</p>
</section>
</section>
<section id="chirps-precipitation-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="chirps-precipitation-data">CHIRPS precipitation data</h2>
<p>For this post, we will use precipitation data from <a href="https://www.chc.ucsb.edu/data/chirps">CHIRPS</a>, a quasi-global gridded rainfall time eries with data from 1981 to the near-present.<span class="citation" data-cites="Funk2015"><sup><a href="#ref-Funk2015" role="doc-biblioref">5</a></sup></span> CHIRPS is frequently used in health, agricultural, and hydrological research because of its relatively high spatial and temporal resolution, and validation studies have shown it to perform better than other leading precipitation models across several metrics.<span class="citation" data-cites="Pena-Guerrero2022 Pyarali2022"><sup><a href="#ref-Pena-Guerrero2022" role="doc-biblioref">6</a>,<a href="#ref-Pyarali2022" role="doc-biblioref">7</a></sup></span></p>
<p>Importantly, the CHIRPS data are provided as <strong>raster data</strong>, not vector data. Instead of representing precipitation with a set of polygons or points (as with vector data), raster data represent geographic features in a <em>grid</em>, where each cell in the grid is associated with a particular value. In our case, each cell is associated with a single daily precipitation value (in millimeters).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/plp2.png" class="img-fluid figure-img"></p>
<figcaption>Comparison of vector and raster data models<span class="citation" data-cites="Minn"><sup><a href="#ref-Minn" role="doc-biblioref">4</a></sup></span></figcaption>
</figure>
</div>
<p>sf doesn’t provide support for raster data—instead, we’ll turn to the <code>{terra}</code> package.</p>
<section id="raster-data" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="raster-data">Raster data</h3>
<p>terra has rapidly become the go-to R package for working with raster data, and it is set to supersede the raster package, which was formerly used for raster operations.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p></p><div class="hex"> <a href="https://rspatial.github.io/terra/index.html" class="hex"> <img src="../../images/hex/terra.png" class="hex-img"> </a> <p class="hex-cap">© Robert J. Hijmans et al. (GPL &gt;=3)</p> </div><p></p>
</div></div><p>In most cases, terra provides much faster processing than does the raster package. The magic behind terra is that it avoids reading many raster images into R at once. Instead, it reads <em>metadata</em> about each image—information about its spatial extent, coordinate reference system, pixel count, and so on.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
raster Package Retirement
</div>
</div>
<div class="callout-body-container callout-body">
<p>At the time of writing, the raster package is still available on CRAN, but it will be retired soon. You may see other resources referencing the raster package, but we suggest relying only on terra to ensure that your code is robust to the upcoming retirement.</p>
</div>
</div>
<section id="installing-terra" class="level4">
<h4 class="anchored" data-anchor-id="installing-terra">Installing terra</h4>
<p>You’ll need the same operating system <a href="#installing-sf">dependencies</a> required for sf to use terra to its full potential. If you’ve already got those set up for sf, it should be easy to install terra with <code>install.packages("terra")</code>. If not, follow <a href="https://rspatial.github.io/terra/index.html#installation">these instructions</a> to set up the package.</p>
</section>
</section>
<section id="loading-chirps-data" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="loading-chirps-data">Loading CHIRPS data</h3>
<p>The complete CHIRPS precipitation data series can be downloaded directly from the <a href="https://data.chc.ucsb.edu/products/CHIRPS-2.0/">UCSB Climate Hazards Center</a>. However, because storing global data can require significant space, most users will likely want to download data for a specific area of interest.</p>
<p>There are two primary ways to go about downloading CHIRPS data for a particular area:</p>
<ol type="1">
<li>Select data interactively through the CHIRPS API provider: <a href="https://climateserv.servirglobal.net/">ClimateSERV</a>. ClimateSERV hosts a graphical user interface (GUI) that allows you to select an area of interest on a map.</li>
<li>Access data through the CHIRPS API using the API client tools provided by the <code>{chirps}</code> package.</li>
</ol>
<p>The first option has the advantage of being visual and intuitive. However, if you need to update your data for a new area or time range, you’ll have to go through the manual download process again.</p>
<p>In contrast, the second option prioritizes reproducibility and adaptability: updating the data used in your analysis is a matter of adjusting just a few lines of code. However, your R session will be occupied while downloading data, which can take a fair amount of time for long time series.</p>
<section id="option-1-climateserv" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="option-1-climateserv">Option 1: ClimateSERV</h4>
<p>First, navigate to the <a href="https://climateserv.servirglobal.net/map">ClimateSERV Map</a>. From there, open the <em>Statistical Query</em> toolbar on the top of the left sidebar and click <strong>Select</strong>. Click <strong>Country</strong> under the <em>Select features by</em> dropdown. Then, click on the country of interest—in this case, Burkina Faso (in West Africa).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The ClimateSERV interface may not work properly on all web browsers (e.g.&nbsp;Firefox). If you have difficulty, try opening the interface in a different browser.</p>
</div>
</div>
<div class="cell page-columns page-full" data-layout-align="center">
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="images/climateserv2.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Once you’ve indicated the country of interest, change the type of request to <strong>Download Raw Data</strong> and the download format to <strong>TIF</strong>. Finally, adjust the date range to start on <strong>01/01/2001</strong> and end on <strong>12/31/2010</strong>. This will give us a 10-year range running up to the survey year, allowing us to calculate a long-run average.</p>
<p>Finally, click <strong>Submit Query</strong> to download the daily rainfall totals. Note that downloading this much data may take a fair amount of time!</p>
<p>Once your request has been processed, you’ll receive a compressed (.zip) folder containing one TIF image for each day in the time span: that’s 3652 files containing many megabytes of raster data. We’ve placed the .zip file in the <code>data</code> directory and renamed it <code>chirps.zip</code>. You can unzip the file in R with <code>unzip()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Unzip and place individual .tif files in a new `data/chirps` directory</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>chirps_files <span class="ot">&lt;-</span> <span class="fu">unzip</span>(<span class="st">"data/chirps.zip"</span>, <span class="at">exdir =</span> <span class="st">"data/chirps"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or, if you prefer to unzip the file manually, you can do so and then list the individual raster files with <code>list.files()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create list of paths to all individual raster files</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>chirps_files <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="st">"data/chirps"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can load raster files with the <code>rast()</code> function from terra. When providing multiple files, terra will stack them so each input file becomes a single layer in a larger <strong>raster stack</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load set of .tif files into into a single raster stack</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>bf_precip <span class="ot">&lt;-</span> <span class="fu">rast</span>(chirps_files)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="option-2-the-chirps-package" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="option-2-the-chirps-package">Option 2: The chirps package</h4>
<p>We can use the <code>get_chirps()</code> function from the <code>{chirps}</code> package to access CHIRPS data via the CHIRPS API. Since we don’t have a map where we can select our region of interest, we’ll have to provide a pre-loaded region representing the area for which we’d like data.</p>
<p>We can use the <code>bf_borders</code> object we created earlier to get data for the Burkina Faso region. We’ll use <code>vect()</code> to convert it to a <code>SpatVector</code> from terra (<code>get_chirps()</code> currently has more robust support for these objects). We’ll also input our desired date range for which to obtain data:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The <code>SpatVector</code> is the main object terra uses to represent vector data. We’ve already shown how to use sf to handle vector data, but terra also provides support for this data model. In general, we find that sf’s vector objects are a little more intuitive, but there are some cases where using terra may make certain operations easier or faster.</p>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the chirps package</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(chirps)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get CHIRPS data from 2001-2010 for Burkina Faso </span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>bf_precip <span class="ot">&lt;-</span> <span class="fu">get_chirps</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vect</span>(bf_borders),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">dates =</span> <span class="fu">c</span>(<span class="st">"2001-01-01"</span>,<span class="st">"2010-12-31"</span>),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">server =</span> <span class="st">"CHC"</span> <span class="co"># Recommended when obtaining data for multiple dates and/or locations</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>get_chirps()</code> obtains data for a rectangular region around the country. For consistency with the results you would get from ClimateSERV (which only downloads data within the country borders), we’ll use terra’s <code>mask()</code> function to remove data from outside the Burkina Faso borders:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bf_precip <span class="ot">&lt;-</span> <span class="fu">mask</span>(bf_precip, bf_borders, <span class="at">touches =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
ClimateSERV vs.&nbsp;chirps
</div>
</div>
<div class="callout-body-container callout-body">
<p>There may be some trivial discrepancies between the data obtained via ClimateSERV and those obtained via the chirps package. When creating this post, we used data obtained via ClimateSERV.</p>
<p>If you instead obtained data from chirps, your values may differ slightly from those we present below. These differences shouldn’t meaningfully affect any of the operations we demonstrate.</p>
</div>
</div>
</section>
</section>
<section id="spatraster-objects" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="spatraster-objects"><code>SpatRaster</code> objects</h3>
<p>Regardless of the method you chose to access the CHIRPS data, you should now have a <code>SpatRaster</code> object from terra containing the raster stack of precipitation data covering the entirety of Burkina Faso from 2001 to 2010:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bf_precip</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; class       : SpatRaster </span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; dimensions  : 115, 159, 3652  (nrow, ncol, nlyr)</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; resolution  : 0.05, 0.05  (x, y)</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; extent      : -5.549997, 2.400003, 9.349999, 15.1  (xmin, xmax, ymin, ymax)</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; coord. ref. : lon/lat WGS 84 (EPSG:4326) </span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sources     : 20010101.tif  </span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;               20010102.tif  </span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;               20010103.tif  </span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;               ... and 3649 more sources</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; names       : 20010101, 20010102, 20010103, 20010104, 20010105, 20010106, ...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see, this raster layer contains 115 rows and 159 columns of pixels. The value in each pixel represents the rainfall (in millimeters) for an area 0.05 degrees longitude by 0.05 degrees latitude (shown in the <code>resolution</code> field).</p>
<p>Each of the 3652 layers in the <code>SpatRaster</code> represents the CHIRPS precipitation values for a single day of the 10-year period between 2001 and 2010.</p>
<p>To better understand this structure, we can visualize the rainfall patterns for one of these days. We’ll first need to select an individual layer from the raster stack. We can index layers by name or layer position using <code>[[</code> notation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select a single layer</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (Layer names will vary depending on how you obtained your CHIRPS data)</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>precip_day <span class="ot">&lt;-</span> bf_precip[[<span class="st">"20010719"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once we’ve selected a layer, we can use <code>layer_spatial()</code> to plot it, just as we did for vector objects.</p>
<div class="cell page-columns page-full">
<details class="code-fold">
<summary>Show plot code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create map of rainfall for single day</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    precip_day, </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fu">if_else</span>(<span class="fu">values</span>(precip_day) <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.8</span>), </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_borders, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"#888888"</span>) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_gps,  <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Burkina Faso Rainfall: July 19, 2001"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"CHIRPS precipitation data with DHS cluster locations"</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Rainfall total (mm)"</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: DHS Program and Climate Hazards Center InfraRed Precipitation with Station (CHIRPS)"</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_scale</span>(</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">style =</span> <span class="st">"ticks"</span>, <span class="at">location =</span> <span class="st">"br"</span>), </span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_col =</span> <span class="st">"#999999"</span>,</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">line_col =</span> <span class="st">"#999999"</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"#00263A"</span>, <span class="at">na.value =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>It can be unwieldy to manage many layers of raster data. In the next section, we’ll introduce methods for simplifying these data across both time and space so they can be more easily attached to our DHS survey.</p>
</section>
</section>
</section>
<section id="summarize-precipitation-values" class="level1 page-columns page-full" data-link="Summarize precipitation values">
<h1 data-link="Summarize precipitation values">Summarize precipitation values</h1>
<p>The terra package contains several <a href="https://rspatial.github.io/terra/reference/summarize-generics.html">summary methods</a> we can use to quickly explore summary statistics across all of the layers included in our multi-year timespan. For example, <code>mean()</code> computes the mean daily precipitation value for each pixel location across all layers (days) of our CHIRPS data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean daily precipitation value for each pixel (mm/day)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>bf_precip_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(bf_precip)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>bf_precip_mean</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; class       : SpatRaster </span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; dimensions  : 115, 159, 1  (nrow, ncol, nlyr)</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; resolution  : 0.05, 0.05  (x, y)</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; extent      : -5.549997, 2.400003, 9.349999, 15.1  (xmin, xmax, ymin, ymax)</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; coord. ref. : lon/lat WGS 84 (EPSG:4326) </span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; source(s)   : memory</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; name        :      mean </span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; min value   : 0.8771938 </span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; max value   : 3.1498873</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that this produces another <code>SpatRaster</code> and that the result only has one layer. This makes sense, because <code>mean()</code> uses all of the input raster layers to produce a single average precipitation (in millimeters per day) for each cell.</p>
<p>Since <code>mean()</code> produces another <code>SpatRaster</code>, we can plot the average values for the 10-year time span just as we did with a single day’s worth of precipitation data:</p>
<div class="cell page-columns page-full">
<details class="code-fold">
<summary>Show plot code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_precip_mean, <span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_borders, <span class="at">alpha =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Burkina Faso Average Rainfall: 2001-2010"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"CHIRPS precipitation data"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"10-year average rainfall (mm/day)"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: Climate Hazards Center InfraRed Precipitation with Station (CHIRPS)"</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_scale</span>(</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">style =</span> <span class="st">"ticks"</span>, <span class="at">location =</span> <span class="st">"br"</span>),</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_col =</span> <span class="st">"#999999"</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">line_col =</span> <span class="st">"#999999"</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"#FAEFD1"</span>, <span class="at">high =</span> <span class="st">"#00263A"</span>, <span class="at">na.value =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>At this point, our primary data sources still remain completely independent. We know the approximate location of the DHS clusters, and we have a summary of the average daily precipitation across Burkina Faso, but we haven’t linked the two together to create a specific precipitation record for each cluster.</p>
<p>Our remaining task is to <strong>extract</strong> the mean precipitation values from the CHIRPS raster at each of the DHS cluster locations.</p>
<section id="cluster-buffers" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="cluster-buffers">Cluster buffers</h2>
<p>We might think it logical to extract the mean precipitation values at each cluster’s point location. However, recall that our motivating question centered around the idea that precipitation influences health by way of impacting local crop yields. The farms that serve the population of a given cluster won’t necessarily be situated right at the recorded cluster location. Furthermore, each farm is probably impacted by the precipitation patterns in its surrounding area, not only those that occur at its exact location.</p>
<p>With this in mind, it makes sense to generate a summary metric of the precipitation in the <em>general area</em> of each cluster, rather than at the cluster point locations. We can accomplish this by creating <strong>buffer zones</strong> around each cluster coordinate.</p>
<p>We can use <code>st_buffer()</code> to create an appropriately sized buffer zone around the displaced GPS coordinates for each cluster. However, sf’s geometrical operations (powered by GEOS) assume that the input data are in <em>meters</em>, and our data are currently in <em>degrees</em>.</p>
<p>Therefore, we first need to <strong>project</strong> our GPS coordinates into a new coordinate reference system, or CRS. We will use the <a href="https://pubs.usgs.gov/fs/2001/0077/report.pdf">UTM Coordinate System</a> Zone 30N for our projection, which provides limited distortion for Burkina Faso. The <a href="https://epsg.io/about">EPSG</a> code for this UTM zone is 32630, which we can provide to <code>st_transform()</code> to project our data:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Map projections constitute an entire topic on their own. To learn more about projected coordinate systems, there are countless resources online, like <a href="http://downloads2.esri.com/support/documentation/ao_/710Understanding_Map_Projections.pdf">this treatment</a> from <a href="https://www.esri.com/en-us/home">ESRI</a></p>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Project cluster locations to the UTM 30N reference system</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>bf_gps <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(bf_gps, <span class="at">crs =</span> <span class="dv">32630</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use <code>st_geometry()</code> to see a summary of our sf object’s geometry. Note that the <code>Projected CRS</code> now shows <code>UTM zone 30N</code>, and that our data are now stored in meters, rather than degrees:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(bf_gps)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geometry set for 541 features </span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geometry type: POINT</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dimension:     XY</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Bounding box:  xmin: 234659.3 ymin: 1092462 xmax: 1039190 ymax: 1645174</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Projected CRS: WGS 84 / UTM zone 30N</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; First 5 geometries:</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POINT (521084.1 1117516)</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POINT (400626 1148510)</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POINT (508145.5 1092462)</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POINT (590542.4 1500704)</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POINT (449803.2 1376723)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>If you need to check your work, you can always access the current CRS of your data with <code>st_crs()</code>.</p>
</div></div><p>Now that we’re working in meters, we can buffer our points using <code>st_buffer()</code>. The appropriate buffer distance will depend on your specific research question of interest. For this demonstration, we’ll create a 10-kilometer (10,000 meter) buffer by setting <code>dist = 10000</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>bf_gps <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(bf_gps, <span class="at">dist =</span> <span class="dv">10000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We see that the geometry column now describes <code>POLYGON</code> geometries rather than <code>POINT</code> geometries. Each polygon is defined by a series of points that form the circumference of the buffer zone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(bf_gps)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geometry set for 541 features </span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geometry type: POLYGON</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dimension:     XY</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Bounding box:  xmin: 224659.3 ymin: 1082462 xmax: 1049190 ymax: 1655174</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Projected CRS: WGS 84 / UTM zone 30N</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; First 5 geometries:</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POLYGON ((531084.1 1117516, 531070.3 1116993, 5...</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POLYGON ((410626 1148510, 410612.3 1147987, 410...</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POLYGON ((518145.5 1092462, 518131.8 1091939, 5...</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POLYGON ((600542.4 1500704, 600528.7 1500181, 6...</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; POLYGON ((459803.2 1376723, 459789.5 1376200, 4...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’re finished measuring distance in meters, so we’ll again use <code>st_transform()</code> to revert back to degrees of latitude and longitude (EPSG 4326) for consistency with our other maps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bf_gps <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(bf_gps, <span class="at">crs =</span> <span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell page-columns page-full">
<details class="code-fold">
<summary>Show plot code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_borders, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_gps, <span class="at">fill =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Buffered DHS Cluster Locations"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Burkina Faso: 2010"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: DHS Program"</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_scale</span>(</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">style =</span> <span class="st">"ticks"</span>, <span class="at">location =</span> <span class="st">"br"</span>), </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_col =</span> <span class="st">"#999999"</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">line_col =</span> <span class="st">"#999999"</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Handling cluster displacement
</div>
</div>
<div class="callout-body-container callout-body">
<p>Previously, we discussed the fact that the cluster coordinates provided by The DHS Program are <a href="#displacement-rules">displaced</a> from their true locations. While we don’t need to address this for our precipitation data, there may be other cases where it is useful to obtain a more precise location for each cluster (for instance, if working with road networks or other fine-grained data).</p>
<p>In these cases, you can certainly buffer points conditionally on other values in the data by providing a conditional statement to the buffer <code>dist</code> argument. For instance, to buffer urban clusters (<code>URBAN_RURA == "U"</code>) by 2000 meters and other clusters by 5000 meters, use an <code>if_else()</code> statement:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_buffer</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  bf_gps, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dist =</span> <span class="fu">if_else</span>(bf_gps<span class="sc">$</span>URBAN_RURA <span class="sc">==</span> <span class="st">"U"</span>, <span class="dv">2000</span>, <span class="dv">5000</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="aggregating-rainfall-within-cluster-regions" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="aggregating-rainfall-within-cluster-regions">Aggregating rainfall within cluster regions</h2>
<p>Now that we have buffered cluster regions, we can focus on combining our two data sources. Let’s zoom in on a single cluster as an example. We’ll use the cluster with <code>DHSCLUST</code> number <code>160</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>clust <span class="ot">&lt;-</span> bf_gps <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DHSCLUST <span class="sc">==</span> <span class="dv">160</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To simplify this example, we’ll use terra’s <code>crop()</code> to restrict our raster to the cells surrounding this cluster:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>precip_clust <span class="ot">&lt;-</span> <span class="fu">crop</span>(bf_precip_mean, clust, <span class="at">snap =</span> <span class="st">"out"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell page-columns page-full">
<details class="code-fold">
<summary>Show plot code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(precip_clust, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(clust, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Rainfall: 2001-2010"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Single DHS cluster"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"10-year average rainfall (mm/day)"</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: DHS Program and Climate Hazards Center InfraRed Precipitation with Station (CHIRPS)"</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">low =</span> <span class="st">"#FAEFD1"</span>, </span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">high =</span> <span class="st">"#00263A"</span>, </span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.value =</span> <span class="cn">NA</span>, </span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">2.3</span>, <span class="fl">2.5</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>For demonstration purposes, we’ve used different limits for the color scale in this plot and the next. In general, we’d want to ensure that the colors in this plot map to the same values used in other plots with the same color scheme.</p>
</div></div><p>We see a range of rainfall totals across the 20 pixels in this area. How can we summarize the information contained in these individual pixels into a single estimate of the rainfall for this buffered cluster region?</p>
<p>The most straightforward approach might be to take the mean of all the pixel values that overlap our buffer region. First, we need to obtain the values of the overlapping raster cells. We can use terra’s <code>extract()</code> to obtain the raster cell values from the region defined by an overlapping vector data source (in this case, our example cluster, <code>clust</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extract</span>(bf_precip_mean, clust)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ID     mean</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1   1 2.337887</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2   1 2.329431</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3   1 2.344792</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4   1 2.317271</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5   1 2.343546</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6   1 2.329051</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7   1 2.381871</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8   1 2.367312</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9   1 2.395538</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10  1 2.395361</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 11  1 2.402505</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 12  1 2.415130</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that this provides mean daily precipitation values for 12 different cells. By default, <code>extract()</code> will only extract values from the cells whose <em>center point</em> lies within the overlaid polygon:</p>
<div class="cell page-columns page-full">
<details class="code-fold">
<summary>Show plot code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># New SpatRaster with same extent as bf_precip_mean, but with empty values</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>ext_cells <span class="ot">&lt;-</span> <span class="fu">rast</span>(bf_precip_mean, <span class="at">vals =</span> <span class="cn">NA</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ID cell locations for each cell that is extracted</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>cell_idx <span class="ot">&lt;-</span> <span class="fu">extract</span>(ext_cells, clust, <span class="at">cells =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>cell</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>ext_cells[cell_idx] <span class="ot">&lt;-</span> bf_precip_mean[cell_idx]</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">crop</span>(ext_cells, clust, <span class="at">snap =</span> <span class="st">"out"</span>), </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.8</span>, </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(clust, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Rainfall: 2001-2010"</span>,</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Single DHS cluster"</span>,</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"10-year average rainfall (mm/day)"</span>,</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: DHS Program and Climate Hazards Center InfraRed Precipitation with Station (CHIRPS)"</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">low =</span> <span class="st">"#FAEFD1"</span>, </span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">high =</span> <span class="st">"#00263A"</span>, </span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.value =</span> <span class="cn">NA</span>, </span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">2.3</span>, <span class="fl">2.5</span>)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>To instead include <em>all</em> cells that intersect the polygon, set <code>touches = TRUE</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>clust_precip <span class="ot">&lt;-</span> <span class="fu">extract</span>(bf_precip_mean, clust, <span class="at">touches =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>clust_precip</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ID     mean</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1   1 2.350189</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2   1 2.319925</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3   1 2.385132</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4   1 2.337887</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5   1 2.329431</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6   1 2.328763</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7   1 2.344792</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8   1 2.317271</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9   1 2.343546</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10  1 2.329051</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 11  1 2.381871</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 12  1 2.367312</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 13  1 2.395538</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 14  1 2.395361</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 15  1 2.393321</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 16  1 2.402505</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 17  1 2.415130</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 18  1 2.395817</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This operation provides the mean daily precipitation values for each of the 18 cells that intersect our cluster region. However, some cells cover a much larger portion of the cluster region than others. To account for the heterogeneity in size, we can set <code>weights = TRUE</code> to include a <code>weight</code> column, which records the proportion of each cell that is covered by the polygon:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>weights = TRUE</code> automatically includes all intersected cells, but those with negligible weights will be removed.</p>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>clust_precip <span class="ot">&lt;-</span> <span class="fu">extract</span>(bf_precip_mean, clust, <span class="at">weights =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>clust_precip</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ID     mean weight</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1   1 2.385132   0.20</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2   1 2.337887   0.90</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3   1 2.329431   0.94</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4   1 2.328763   0.33</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5   1 2.344792   0.70</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6   1 2.317271   1.00</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7   1 2.343546   1.00</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8   1 2.329051   0.86</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9   1 2.381871   0.57</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10  1 2.367312   1.00</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 11  1 2.395538   1.00</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 12  1 2.395361   0.74</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 13  1 2.393321   0.03</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 14  1 2.402505   0.47</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 15  1 2.415130   0.53</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 16  1 2.395817   0.09</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then provide the weights to the <code>weighted.mean()</code> function to calculate a weighted mean that is shifted toward the cell values that form a larger proportion of the polygon area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">weighted.mean</span>(clust_precip<span class="sc">$</span>mean, clust_precip<span class="sc">$</span>weight)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 2.358508</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Because this kind of workflow is so common, terra provides a quicker shorthand in <code>extract()</code>. You can use the <code>fun</code> argument to specify an aggregation function at the same time that you extract the raster cell values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract area-weighted average for all cells covered by `clust`</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">extract</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  bf_precip_mean,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  clust,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="co"># Average all extracted values</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="cn">TRUE</span> <span class="co"># Use area weights</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ID     mean</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1  1 2.358508</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>2.358508</code> value represents the area-weighted mean of the 10-year mean precipitation values (in millimeters per day) within the given cluster region.</p>
<section id="scaling-up-for-all-clusters" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="scaling-up-for-all-clusters">Scaling up for all clusters</h3>
<p>To aggregate the rainfall data for each DHS cluster in the sample, we simply scale up. We again use <code>extract()</code>, but we provide our raster of precipitation values for the entire country and the polygons for all of our buffered clusters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average the mean CHIRPS values within each DHS cluster</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>clust_means <span class="ot">&lt;-</span> <span class="fu">extract</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  bf_precip_mean,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  bf_gps, <span class="co"># All clusters included</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fun =</span> <span class="st">"mean"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="cn">TRUE</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="co"># Ignore missing CHIRPS values</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">bind =</span> <span class="cn">TRUE</span> <span class="co"># Recombine with original `bf_gps` data</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By setting <code>bind = TRUE</code>, we can automatically recombine the extracted means with the other cluster data in <code>bf_gps</code>.</p>
<p>We also set <code>na.rm = TRUE</code> to ensure we don’t get missing values for clusters whose regions expand beyond the country borders (where we haven’t downloaded any CHIRPS data). This decision may be reasonable if our interest is in rainfall over local crop-producing regions, and we don’t believe that clusters in border regions obtain substantial inputs from farms outside of the country. (If we wanted to include the rainfall outside of the country borders, we would simply need to expand our bounding box when downloading our CHIRPS data.)</p>
<p>Finally, we’ll convert our cluster means back to an sf object. Notice that there now exists a <code>mean</code> column that stores the weighted mean values for each cluster:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to sf object</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>clust_means <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(clust_means)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>clust_means <span class="sc">|&gt;</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(DHSID, mean, geometry)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Simple feature collection with 541 features and 2 fields</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geometry type: POLYGON</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dimension:     XY</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Bounding box:  xmin: -5.517451 ymin: 9.792417 xmax: 2.049008 ymax: 14.95288</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Geodetic CRS:  WGS 84</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; First 10 features:</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             DHSID     mean                       geometry</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1  BF201000000001 2.758146 POLYGON ((-2.71628 10.10935...</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2  BF201000000002 2.782180 POLYGON ((-3.816453 10.3887...</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3  BF201000000003 3.004422 POLYGON ((-2.834491 9.88283...</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4  BF201000000004 1.678181 POLYGON ((-2.070699 13.5730...</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5  BF201000000005 2.129466 POLYGON ((-3.369883 12.4534...</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6  BF201000000006 2.203529 POLYGON ((-1.991964 12.0449...</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7  BF201000000007 1.113443 POLYGON ((-0.579432 14.3532...</span></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8  BF201000000008 2.110246 POLYGON ((-1.470133 12.3105...</span></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9  BF201000000009 2.281224 POLYGON ((-0.2722169 11.779...</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 BF201000000010 1.722371 POLYGON ((-1.245736 13.2245...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have aggregated rainfall across all clusters, we can plot the average rainfall for each of the 10-kilometer buffered cluster regions. Each cluster region is associated with a single 10-year average rainfall value.</p>
<div class="cell page-columns page-full">
<details class="code-fold">
<summary>Show plot code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(bf_borders, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_spatial</span>(clust_means, <span class="fu">aes</span>(<span class="at">fill =</span> mean), <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Rainfall within Clusters: 2001-2010"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Burkina Faso: 2010 Clusters"</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"10-year average rainfall (mm/day)"</span>,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: DHS Program and Climate Hazards Center InfraRed Precipitation with Station (CHIRPS)"</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_scale</span>(</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">style =</span> <span class="st">"ticks"</span>, <span class="at">location =</span> <span class="st">"br"</span>), </span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_col =</span> <span class="st">"#999999"</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">line_col =</span> <span class="st">"#999999"</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_steps</span>(<span class="at">low =</span> <span class="st">"#FAEFD1"</span>, <span class="at">high =</span> <span class="st">"#00263A"</span>, <span class="at">n.breaks =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.ticks =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/listing-img-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="join-data-sources" class="level1 page-columns page-full">
<h1>Join data sources</h1>
<p>At this point, we have our aggregated CHIRPS data merged with our DHS <em>clusters</em>, but not with the individual DHS survey <em>responses</em>.</p>
<p>To accomplish this last task, we need to merge the cluster means with the survey responses, based on the cluster where each response was recorded. This information is stored in the <code>DHSID</code> variable provided by IPUMS DHS.</p>
<p>We’ll use dplyr’s <code>right_join()</code> to merge the survey responses with the mean precipitation values for each cluster, matching records using their <code>DHSID</code> code. Using <code>right_join()</code> ensures that responses from clusters with no location information (which have been filtered out of <code>clust_means</code>) are not included in the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join survey responses and cluster precipitation values, based on</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the cluster where each response was recorded (DHSID)</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>dhs_chirps <span class="ot">&lt;-</span> <span class="fu">right_join</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  dhs,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>(clust_means), <span class="co"># remove geometry for simplicity in output</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">"DHSID"</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can finally link the 10-year mean precipitation value to each sample participant’s outcomes. To demonstrate, we clean up the <code>HWHAZWHO</code> variable and visualize the relationship between 10-year average precipitation and childrens’ height-for-age in Z-scores:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>ipumsr includes helper functions to view the metadata for IPUMS variables. For instance, <code>ipums_val_labels()</code> can show us the missing value codes for a given variable, which we can use when cleaning our data.</p>
</div></div><div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean up HWHAZWHO for plotting</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>dhs_chirps_recode <span class="ot">&lt;-</span> dhs_chirps <span class="sc">|&gt;</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HWHAZWHO <span class="sc">&lt;</span> <span class="dv">9995</span>) <span class="sc">|&gt;</span> <span class="co"># Remove missing HWHAZWHO values</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HWHAZWHO =</span> HWHAZWHO <span class="sc">/</span> <span class="dv">100</span>) <span class="co"># Recode decimal place based on IPUMS documentation</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatterplot of mean precipitation value vs. HWHAZWHO </span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> mean, <span class="at">y =</span> HWHAZWHO, <span class="at">fill =</span> mean), </span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dhs_chirps_recode,</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"#999999"</span>, </span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape =</span> <span class="dv">21</span>,</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span>,</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.8</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Rainfall and Stunting"</span>,</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Burkina Faso: 2010 Clusters"</span>,</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"10-year average rainfall (mm/day)"</span>,</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Height for Age Z-Score"</span>,</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"10-year average rainfall (mm/day)"</span>,</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: IPUMS DHS, DHS Program, and Climate Hazards Center InfraRed Precipitation with Station (CHIRPS)"</span></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"#FAEFD1"</span>, <span class="at">high =</span> <span class="st">"#00263A"</span>, <span class="at">na.value =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="index_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img column-page" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Since our rainfall metric is now linked to each individual’s survey response, we can include average rainfall as a predictor when analyzing the health outcomes provided by IPUMS DHS.</p>
</section>
<section id="final-thoughts" class="level1">
<h1>Final thoughts</h1>
<p>This post has introduced several core concepts for including spatial data in an analysis, including:</p>
<ul>
<li>the distinction between vector and raster data</li>
<li>the main packages (sf and terra) used for working with spatial data in R</li>
<li>methods for summarizing longitudinal spatial data across time</li>
<li>spatial buffering and methods for aggregating raster values within polygons</li>
<li>the importance of considering the geographic context of spatial data when deciding the most appropriate way to include such data in an analysis</li>
</ul>
<p>That being said, many of the techniques we introduced will be too simplistic for most analyses.</p>
<p>For instance, a single long-run average is unlikely to capture much nuance in the way precipitation influences nutrition. Instead, it might be more meaningful to determine precipitation patterns at the points in the growing season when crops are most vulnerable. Or we could investigate local environmental conditions only for time periods surrounding each child’s birth.</p>
<p>Furthermore, our CHIRPS data span until the end of 2010, but the health interview responses come from <em>before</em> the end of 2010, meaning that some of our rainfall data can’t possibly be causally linked to the health responses.</p>
<p>Using geographic data therefore requires careful planning and thought. Nonetheless, the workflow and methods introduced in this post should give you a solid foundation from which to start thinking about how to integrate spatial data into analyses of IPUMS DHS data.</p>

</section>

<div id="quarto-appendix" class="default"><section id="getting-help" class="level2 appendix"><h2 class="anchored quarto-appendix-heading">Getting Help</h2><div class="quarto-appendix-contents">

<p>Questions or comments? Check out the <a href="https://forum.ipums.org">IPUMS User Forum</a> or reach out to IPUMS User Support at ipums@umn.edu.</p>



</div></section><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Mirza2011" class="csl-entry" role="listitem">
1. Mirza, M. M. Q. (2011). Climate change, flooding in <span>S</span>outh <span>A</span>sia and implications. <em>Regional Environmental Change</em>, <em>11</em>, 95–107. <a href="https://doi.org/10.1007/S10113-010-0184-7">https://doi.org/10.1007/S10113-010-0184-7</a>
</div>
<div id="ref-Martens1997" class="csl-entry" role="listitem">
2. Martens, W. J. M., Jetten, T. H., &amp; Focks, D. A. (1997). Sensitivity of malaria, schistosomiasis and dengue to global warming. <em>Climatic Change</em>, <em>35</em>, 145–156. <a href="https://doi.org/10.1023/A:1005365413932">https://doi.org/10.1023/A:1005365413932</a>
</div>
<div id="ref-Lesk2016" class="csl-entry" role="listitem">
3. Lesk, C., Rowhani, P., &amp; Ramankutty, N. (2016). Influence of extreme weather disasters on global crop production. <em>Nature</em>, <em>529</em>, 84–87. <a href="https://doi.org/10.1038/nature16467">https://doi.org/10.1038/nature16467</a>
</div>
<div id="ref-Minn" class="csl-entry" role="listitem">
4. Minn, M. (n.d.). <em>Points vs. <span class="nocase">l</span>ines vs. <span class="nocase">p</span>olygons</em>. <a href="https://michaelminn.net/tutorials/arcgis-pro-terrain/">https://michaelminn.net/tutorials/arcgis-pro-terrain/</a>
</div>
<div id="ref-Funk2015" class="csl-entry" role="listitem">
5. Funk, C., Peterson, P., Landsfeld, M., Pedreros, D., Verdin, J., Shukla, S., Husak, G., Rowland, J., Harrison, L., Hoell, A., &amp; Michaelsen, J. (2015). The climate hazards infrared precipitation with stations—a new environmental record for monitoring extremes. <em>Scientific Data</em>, <em>2</em>, 1–21. <a href="https://doi.org/10.1038/sdata.2015.66">https://doi.org/10.1038/sdata.2015.66</a>
</div>
<div id="ref-Pena-Guerrero2022" class="csl-entry" role="listitem">
6. Peña-Guerrero, M. D., Umirbekov, A., Tarasova, L., &amp; Müller, D. (2022). Comparing the performance of high-resolution global precipitation products across topographic and climatic gradients of <span>C</span>entral <span>A</span>sia. <em>International Journal of Climatology</em>, <em>42</em>, 5554–5569. <a href="https://doi.org/10.1002/JOC.7548">https://doi.org/10.1002/JOC.7548</a>
</div>
<div id="ref-Pyarali2022" class="csl-entry" role="listitem">
7. Pyarali, K., Peng, J., Disse, M., &amp; Tuo, Y. (2022). Development and application of high resolution SPEI drought dataset for <span>C</span>entral <span>A</span>sia. <em>Scientific Data</em>, <em>9</em>, 1–14. <a href="https://doi.org/10.1038/s41597-022-01279-5">https://doi.org/10.1038/s41597-022-01279-5</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ipums\.github\.io\/dhs-research-hub");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Developed by <a href="https://www.ipums.org">IPUMS</a> at the University of Minnesota<br>Licensed under the <a href="https://www.mozilla.org/en-US/MPL/2.0/">Mozilla Public License Version 2.0</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>