`%||%` <- function(x, y) {
  if (is_null(x)) y else x
}

theme_dhs_base <- function() {
  ggplot2::`%+replace%`(
    ggplot2::theme_minimal(),
    ggplot2::theme(
      text = ggplot2::element_text(family = "cabrito", size = 10), 
      plot.title = ggplot2::element_text(
        hjust = 0,
        size = 18, 
        color = "#00263A", # IPUMS navy
        margin = ggplot2::margin(b = 7)
      ), 
      plot.subtitle = ggplot2::element_text(
        size = 12, 
        hjust = 0,
        color = "#00000099",
        margin = ggplot2::margin(b = 10)
      ),
      plot.caption = ggplot2::element_text(
        size = 10,
        hjust = 1,
        color = "#00000099",
        margin = ggplot2::margin(t = 5)
      ),
      legend.position = "bottom"
    )
  )
}

# renv does not appear to install proj along with sf.
#
# Adding either the global sf installation location (which includes a `proj`
# directory) or an external installation of PROJ to the search path appears to
# resolve the issue.
#
# However, this means that other users will have to both have an renv sf installation
# as well as a global sf installation.
#
# Not yet sure of a better way to enable this, but going to keep this for now.
#
# TODO: Add this to developer walkthrough if we need devs to handle proj
# installation themselves.
set_proj_search_paths <- function(path = NULL) {
  # path to global sf installation
  path <- path %||% "/Users/robe2037/Library/R/x86_64/4.3/library/sf/proj"
  
  # OR: path to direct PROJ installation
  # "/opt/homebrew/Cellar/proj/9.3.0/share/proj"
  
  sf_proj_search_paths(paths = c(sf_proj_search_paths(), path))
}

# theme_pma_rainfall <- function(title, 
#                                subtitle = NULL, 
#                                show_legend = TRUE,
#                                manual_grid = FALSE) {
#   components <- list(
#     theme_minimal() %+replace% 
#       theme(
#         text = element_text(family = "cabrito", size = 10), 
#         plot.title = element_text(
#           hjust = 0,
#           size = 18, 
#           color = "#00263A", # IPUMS navy
#           margin = margin(b = 5)
#         ), 
#         plot.subtitle = element_text(
#           size = 12, 
#           hjust = 0,
#           margin = margin(b = 10)
#         )
#       ),
#     labs(
#       title = title, 
#       subtitle = subtitle,
#       fill = "Rainfall total (mm)",
#       size = "EA displacement buffer",
#       x = NULL,
#       y = NULL
#     ),
#     guides(size = guide_legend(override.aes = list(alpha = 1))),
#     annotation_scale(aes(style = "ticks", location = "br")),
#     # if(show_legend) {
#     #   c(
#     #     geom_point(
#     #       mapping = aes(size = URBAN + 1, x = 0, y = 14),
#     #       data = data,
#     #       alpha = 0, 
#     #       shape = 21, 
#     #       fill = "white"
#     #     ),
#     #     scale_size(
#     #       breaks = c(1, 2), 
#     #       range = c(.75, 3), 
#     #       labels = c("Urban (2 km)", "Rural (5 km)")
#     #     )
#     #   )
#     # },
#     if (manual_grid) { 
#       c(
#         scale_x_continuous(breaks = seq(from = -0.4, to = -0.2, by = 0.025)),
#         scale_y_continuous(breaks = seq(from = 13.4, to = 13.6, by = 0.025)),
#         scale_fill_gradient2(high = "#BEC4CB")
#       )
#     }
#   )
# }

# Build hyperlink to an R function or package, ensuring
# consistency with links generated by `downlit` package in code blocks on blog.
#
# If linking to a function, provide the function name in
# pkg::fun syntax (e.g. readr::read_csv). If no `::` is found, `fun` is
# assumed to be the name of a package. The provided `fun` does not need to
# be a string.
# 
# Note that while some packages provide documentation under their package name
# (e.g. pkg::pkg), the automatically generated link for this expression may
# be different from that generated when calling library(pkg). Therefore,
# if linking to a package, the returned link will be that produced when 
# calling library(pkg). (If you want the documentation for pkg::pkg, simply
# provide this to the `fun` argument instead.)
# 
# By default, only the function or package name is displayed in the output text.
# To display different text, a string passed to the `alt_text` argument will
# be displayed instead.
funlink <- function(fun, alt_text = NULL) {
  
  fun <- deparse(substitute(fun))
  
  stopifnot(length(fun) == 1)
  
  is_fun <- stringr::str_detect(fun, "::")
  
  # If not provided as pkg::fun, assume we are linking to a package
  if (!is_fun) {
    display_name <- fun
    fun <- paste0("library(", fun, ")")
  } else {
    display_name <- stringr::str_split(fun, "::")[[1]][2]
  }
  
  url <- downlit::autolink_url(fun)
  
  if (is.na(url)) {
    rlang::abort(
      paste0("Unable to find link for function `", fun, "`")
    )
  } else if (!is_fun && stringr::str_detect(url, "library.html$")) {
    # `autolink_url` returns a generic link for `library` docs when 
    # package is not found. Throw error instead:
    rlang::abort(
      paste0("Unable to find link for package `", display_name, "`")
    )
  }
  
  if (!is.null(alt_text)) {
    display_name <- alt_text
  }
  
  paste0("[", display_name, "](", url, ")")
  
}

# Get the hex sticker for a package (e.g. for images within aside tags)
# Must be included in `images/hex` and recorded in `images/hex/inventory.csv`
hex <- function(pkg){
  inventory <- readr::read_csv(
    here::here("images/hex/inventory.csv"), 
    show_col_types = FALSE,
    progress = FALSE
  )
  
  if(pkg %in% inventory$package){
    inventory <- dplyr::filter(inventory, package == pkg)
    
    htmltools::div(
      class = "hex",
      htmltools::a(
        href = inventory$url,
        class = "hex",
        htmltools::img(
          src = file.path("../../images/hex", paste0(pkg, ".png")),
          class = "hex-img"
        )
      ),
      htmltools::p(
        class = "hex-cap",
        paste("©", inventory$owner, paste0("(", inventory$license, ")"))
      )
    )
  } else {
    rlang::abort(c(
      paste0("The `", pkg, "` package has no available hex logo"),
      "i" = "Consider downloading one to `images/hex`",
      "i" = "If you do, please add it to `images/hex/inventory.csv`" 
    ))
  }
}
